// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjLBwNdNoLGM_QOWbA6uki2Q6bpl2EUV8',
    appId: '1:188240394333:web:fddfcb49fbc55653a0b5b4',
    messagingSenderId: '188240394333',
    projectId: 'ararat-f83d7',
    authDomain: 'ararat-f83d7.firebaseapp.com',
    storageBucket: 'ararat-f83d7.firebasestorage.app',
    measurementId: 'G-0Y2RL3FHP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mGUm298mlk1bzsngl73rhOstltI86LA',
    appId: '1:188240394333:android:31c73c8427327675a0b5b4',
    messagingSenderId: '188240394333',
    projectId: 'ararat-f83d7',
    storageBucket: 'ararat-f83d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBffBFOlRZhdKLi1FLCJR776Gtuzm0y6u4',
    appId: '1:188240394333:ios:c0dbfb842c35d4e6a0b5b4',
    messagingSenderId: '188240394333',
    projectId: 'ararat-f83d7',
    storageBucket: 'ararat-f83d7.firebasestorage.app',
    iosBundleId: 'com.example.ararat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBffBFOlRZhdKLi1FLCJR776Gtuzm0y6u4',
    appId: '1:188240394333:ios:c0dbfb842c35d4e6a0b5b4',
    messagingSenderId: '188240394333',
    projectId: 'ararat-f83d7',
    storageBucket: 'ararat-f83d7.firebasestorage.app',
    iosBundleId: 'com.example.ararat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjLBwNdNoLGM_QOWbA6uki2Q6bpl2EUV8',
    appId: '1:188240394333:web:0198e34d492ee222a0b5b4',
    messagingSenderId: '188240394333',
    projectId: 'ararat-f83d7',
    authDomain: 'ararat-f83d7.firebaseapp.com',
    storageBucket: 'ararat-f83d7.firebasestorage.app',
    measurementId: 'G-GY79EMBF9F',
  );

}