// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOKLNzHXUTHy4aU2S1dBEk30lGOQ3WHxM',
    appId: '1:301989351145:web:cf8dc2f6ff2b635efc2a78',
    messagingSenderId: '301989351145',
    projectId: 'arara-efa6f',
    authDomain: 'arara-efa6f.firebaseapp.com',
    storageBucket: 'arara-efa6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3BKbiPQ6_yfD81ND1_WR4TufGvzV1nfE',
    appId: '1:301989351145:android:5f0e99f75c74369efc2a78',
    messagingSenderId: '301989351145',
    projectId: 'arara-efa6f',
    storageBucket: 'arara-efa6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUVQVCgoebHVU0RepcvyMTNz0Qmk0Bu7Y',
    appId: '1:301989351145:ios:85df4fa2c17ca3aefc2a78',
    messagingSenderId: '301989351145',
    projectId: 'arara-efa6f',
    storageBucket: 'arara-efa6f.firebasestorage.app',
    iosBundleId: 'com.example.ararat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUVQVCgoebHVU0RepcvyMTNz0Qmk0Bu7Y',
    appId: '1:301989351145:ios:85df4fa2c17ca3aefc2a78',
    messagingSenderId: '301989351145',
    projectId: 'arara-efa6f',
    storageBucket: 'arara-efa6f.firebasestorage.app',
    iosBundleId: 'com.example.ararat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOKLNzHXUTHy4aU2S1dBEk30lGOQ3WHxM',
    appId: '1:301989351145:web:0f2d27532694976ffc2a78',
    messagingSenderId: '301989351145',
    projectId: 'arara-efa6f',
    authDomain: 'arara-efa6f.firebaseapp.com',
    storageBucket: 'arara-efa6f.firebasestorage.app',
  );

}