// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-TX5s4pGJ2-slqy6TWeDW35JJhYxSH4',
    appId: '1:756793988940:web:f8c067d30271745331a1e9',
    messagingSenderId: '756793988940',
    projectId: 'red-reference-434715-m9',
    authDomain: 'red-reference-434715-m9.firebaseapp.com',
    storageBucket: 'red-reference-434715-m9.firebasestorage.app',
    measurementId: 'G-K7F4H0CDEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQxPl-IcdpBBdD1-xoks3l302KqXi1JSk',
    appId: '1:756793988940:android:86d098453935339731a1e9',
    messagingSenderId: '756793988940',
    projectId: 'red-reference-434715-m9',
    storageBucket: 'red-reference-434715-m9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUoyfTjCwWT89oruOLNhxHpOtg9PjtiuM',
    appId: '1:756793988940:ios:8e3bc53d8c363b1b31a1e9',
    messagingSenderId: '756793988940',
    projectId: 'red-reference-434715-m9',
    storageBucket: 'red-reference-434715-m9.firebasestorage.app',
    iosBundleId: 'com.example.ararat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUoyfTjCwWT89oruOLNhxHpOtg9PjtiuM',
    appId: '1:756793988940:ios:8e3bc53d8c363b1b31a1e9',
    messagingSenderId: '756793988940',
    projectId: 'red-reference-434715-m9',
    storageBucket: 'red-reference-434715-m9.firebasestorage.app',
    iosBundleId: 'com.example.ararat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-TX5s4pGJ2-slqy6TWeDW35JJhYxSH4',
    appId: '1:756793988940:web:0da4a8eae8044ddb31a1e9',
    messagingSenderId: '756793988940',
    projectId: 'red-reference-434715-m9',
    authDomain: 'red-reference-434715-m9.firebaseapp.com',
    storageBucket: 'red-reference-434715-m9.firebasestorage.app',
    measurementId: 'G-986FL7E2XW',
  );
}
